from trade.strategies.trending.dualsma import DualSmaStrategy
from trade.strategies.trending.nadaraya_watson import DualNadarayaKernelStrategy
from trade.strategies.scalping.minmax import MinMaxStrategy